import { ScientificConstant, UnitCategory } from '../types/calculator';

export const SCIENTIFIC_CONSTANTS: ScientificConstant[] = [
  // Universal / Physics
  {
    symbol: 'c',
    name: 'Speed of Light in Vacuum',
    value: 299792458,
    formatted: '2.99792458 × 10⁸',
    unit: 'm / s',
    category: 'Universal',
    description: 'Exact speed at which conventional matter and light travel in vacuum.',
  },
  {
    symbol: 'h',
    name: 'Planck Constant',
    value: 6.62607015e-34,
    formatted: '6.62607015 × 10⁻³⁴',
    unit: 'J · s',
    category: 'Universal',
    description: 'Relates photon energy to its frequency in quantum mechanics.',
  },
  {
    symbol: 'ħ',
    name: 'Reduced Planck Constant (h-bar)',
    value: 1.054571817e-34,
    formatted: '1.05457182 × 10⁻³⁴',
    unit: 'J · s',
    category: 'Universal',
    description: 'Fundamental constant in quantum mechanics equal to h / (2π).',
  },
  {
    symbol: 'G',
    name: 'Newtonian Constant of Gravitation',
    value: 6.6743e-11,
    formatted: '6.67430 × 10⁻¹¹',
    unit: 'm³ / (kg · s²)',
    category: 'Universal',
    description: 'Defines the gravitational attraction between massive bodies.',
  },
  {
    symbol: 'e_charge',
    name: 'Elementary Electric Charge',
    value: 1.602176634e-19,
    formatted: '1.60217663 × 10⁻¹⁹',
    unit: 'C',
    category: 'Physics',
    description: 'Magnitude of the electric charge carried by a single proton or electron.',
  },
  {
    symbol: 'm_e',
    name: 'Electron Rest Mass',
    value: 9.1093837015e-31,
    formatted: '9.10938370 × 10⁻³¹',
    unit: 'kg',
    category: 'Physics',
    description: 'Invariant mass of a stationary electron.',
  },
  {
    symbol: 'm_p',
    name: 'Proton Rest Mass',
    value: 1.67262192369e-27,
    formatted: '1.67262192 × 10⁻²⁷',
    unit: 'kg',
    category: 'Physics',
    description: 'Invariant mass of a stationary proton.',
  },
  {
    symbol: 'm_n',
    name: 'Neutron Rest Mass',
    value: 1.67492749804e-27,
    formatted: '1.67492750 × 10⁻²⁷',
    unit: 'kg',
    category: 'Physics',
    description: 'Invariant mass of a stationary neutron.',
  },
  {
    symbol: 'k_B',
    name: 'Boltzmann Constant',
    value: 1.380649e-23,
    formatted: '1.380649 × 10⁻²³',
    unit: 'J / K',
    category: 'Physics',
    description: 'Relates the average relative kinetic energy of particles in a gas with thermodynamic temperature.',
  },
  {
    symbol: 'ε₀',
    name: 'Vacuum Electric Permittivity',
    value: 8.8541878128e-12,
    formatted: '8.85418781 × 10⁻¹²',
    unit: 'F / m',
    category: 'Physics',
    description: 'Capability of a vacuum to permit electric field lines.',
  },
  {
    symbol: 'μ₀',
    name: 'Vacuum Magnetic Permeability',
    value: 1.25663706212e-6,
    formatted: '1.25663706 × 10⁻⁶',
    unit: 'N / A²',
    category: 'Physics',
    description: 'Magnetic constant in vacuum.',
  },
  {
    symbol: 'σ',
    name: 'Stefan-Boltzmann Constant',
    value: 5.670374419e-8,
    formatted: '5.67037442 × 10⁻⁸',
    unit: 'W / (m² · K⁴)',
    category: 'Physics',
    description: 'Total energy radiated per unit surface area of a black body per unit time.',
  },

  // Chemistry
  {
    symbol: 'N_A',
    name: 'Avogadro Constant',
    value: 6.02214076e23,
    formatted: '6.02214076 × 10²³',
    unit: 'mol⁻¹',
    category: 'Chemistry',
    description: 'Number of constituent particles in one mole of a substance.',
  },
  {
    symbol: 'R',
    name: 'Molar Universal Gas Constant',
    value: 8.314462618,
    formatted: '8.31446262',
    unit: 'J / (mol · K)',
    category: 'Chemistry',
    description: 'Equivalent to the Boltzmann constant multiplied by the Avogadro constant.',
  },
  {
    symbol: 'F',
    name: 'Faraday Constant',
    value: 96485.33212,
    formatted: '96485.3321',
    unit: 'C / mol',
    category: 'Chemistry',
    description: 'Electric charge per mole of electrons.',
  },

  // Astronomy
  {
    symbol: 'g₀',
    name: 'Standard Earth Gravity',
    value: 9.80665,
    formatted: '9.80665',
    unit: 'm / s²',
    category: 'Astronomy',
    description: 'Standard nominal gravitational acceleration of an object in a vacuum near the surface of Earth.',
  },
  {
    symbol: 'AU',
    name: 'Astronomical Unit',
    value: 149597870700,
    formatted: '1.49597871 × 10¹¹',
    unit: 'm',
    category: 'Astronomy',
    description: 'Roughly the distance from Earth to the Sun.',
  },
  {
    symbol: 'ly',
    name: 'Light Year',
    value: 9.4607304725808e15,
    formatted: '9.46073047 × 10¹⁵',
    unit: 'm',
    category: 'Astronomy',
    description: 'Distance that light travels in vacuum in one Julian year.',
  },

  // Mathematics
  {
    symbol: 'π',
    name: 'Pi (Archimedes Constant)',
    value: Math.PI,
    formatted: '3.141592653589793',
    unit: 'dimensionless',
    category: 'Mathematics',
    description: 'Ratio of a circle’s circumference to its diameter.',
  },
  {
    symbol: 'e',
    name: 'Euler Number',
    value: Math.E,
    formatted: '2.718281828459045',
    unit: 'dimensionless',
    category: 'Mathematics',
    description: 'Base of the natural logarithm.',
  },
  {
    symbol: 'φ',
    name: 'Golden Ratio',
    value: 1.618033988749895,
    formatted: '1.618033988749895',
    unit: 'dimensionless',
    category: 'Mathematics',
    description: 'Mathematical ratio (1 + √5) / 2 found widely in geometry and nature.',
  },
];

export const UNIT_CATEGORIES: UnitCategory[] = [
  {
    id: 'length',
    name: 'Length',
    iconName: 'Ruler',
    units: [
      { id: 'm', name: 'Meter', symbol: 'm', toBase: v => v, fromBase: v => v },
      { id: 'km', name: 'Kilometer', symbol: 'km', toBase: v => v * 1000, fromBase: v => v / 1000 },
      { id: 'cm', name: 'Centimeter', symbol: 'cm', toBase: v => v * 0.01, fromBase: v => v / 0.01 },
      { id: 'mm', name: 'Millimeter', symbol: 'mm', toBase: v => v * 0.001, fromBase: v => v / 0.001 },
      { id: 'um', name: 'Micrometer', symbol: 'µm', toBase: v => v * 1e-6, fromBase: v => v / 1e-6 },
      { id: 'nm', name: 'Nanometer', symbol: 'nm', toBase: v => v * 1e-9, fromBase: v => v / 1e-9 },
      { id: 'in', name: 'Inch', symbol: 'in', toBase: v => v * 0.0254, fromBase: v => v / 0.0254 },
      { id: 'ft', name: 'Foot', symbol: 'ft', toBase: v => v * 0.3048, fromBase: v => v / 0.3048 },
      { id: 'yd', name: 'Yard', symbol: 'yd', toBase: v => v * 0.9144, fromBase: v => v / 0.9144 },
      { id: 'mi', name: 'Mile', symbol: 'mi', toBase: v => v * 1609.344, fromBase: v => v / 1609.344 },
      { id: 'nmi', name: 'Nautical Mile', symbol: 'nmi', toBase: v => v * 1852, fromBase: v => v / 1852 },
      { id: 'ly', name: 'Light Year', symbol: 'ly', toBase: v => v * 9.4607304725808e15, fromBase: v => v / 9.4607304725808e15 },
    ],
  },
  {
    id: 'mass',
    name: 'Mass & Weight',
    iconName: 'Scale',
    units: [
      { id: 'kg', name: 'Kilogram', symbol: 'kg', toBase: v => v, fromBase: v => v },
      { id: 'g', name: 'Gram', symbol: 'g', toBase: v => v * 0.001, fromBase: v => v * 1000 },
      { id: 'mg', name: 'Milligram', symbol: 'mg', toBase: v => v * 1e-6, fromBase: v => v * 1e6 },
      { id: 'ug', name: 'Microgram', symbol: 'µg', toBase: v => v * 1e-9, fromBase: v => v * 1e9 },
      { id: 't', name: 'Metric Ton', symbol: 't', toBase: v => v * 1000, fromBase: v => v / 1000 },
      { id: 'lb', name: 'Pound', symbol: 'lb', toBase: v => v * 0.45359237, fromBase: v => v / 0.45359237 },
      { id: 'oz', name: 'Ounce', symbol: 'oz', toBase: v => v * 0.028349523125, fromBase: v => v / 0.028349523125 },
      { id: 'stone', name: 'Stone', symbol: 'st', toBase: v => v * 6.35029318, fromBase: v => v / 6.35029318 },
      { id: 'u', name: 'Atomic Mass Unit', symbol: 'u', toBase: v => v * 1.6605390666e-27, fromBase: v => v / 1.6605390666e-27 },
    ],
  },
  {
    id: 'temperature',
    name: 'Temperature',
    iconName: 'Thermometer',
    units: [
      { id: 'c', name: 'Celsius', symbol: '°C', toBase: v => v, fromBase: v => v },
      { id: 'k', name: 'Kelvin', symbol: 'K', toBase: v => v - 273.15, fromBase: v => v + 273.15 },
      { id: 'f', name: 'Fahrenheit', symbol: '°F', toBase: v => (v - 32) * (5 / 9), fromBase: v => v * (9 / 5) + 32 },
      { id: 'r', name: 'Rankine', symbol: '°R', toBase: v => (v - 491.67) * (5 / 9), fromBase: v => (v + 273.15) * (9 / 5) },
    ],
  },
  {
    id: 'energy',
    name: 'Energy',
    iconName: 'Zap',
    units: [
      { id: 'j', name: 'Joule', symbol: 'J', toBase: v => v, fromBase: v => v },
      { id: 'kj', name: 'Kilojoule', symbol: 'kJ', toBase: v => v * 1000, fromBase: v => v / 1000 },
      { id: 'cal', name: 'Calorie (therm.)', symbol: 'cal', toBase: v => v * 4.184, fromBase: v => v / 4.184 },
      { id: 'kcal', name: 'Kilocalorie (food)', symbol: 'kcal', toBase: v => v * 4184, fromBase: v => v / 4184 },
      { id: 'wh', name: 'Watt-hour', symbol: 'Wh', toBase: v => v * 3600, fromBase: v => v / 3600 },
      { id: 'kwh', name: 'Kilowatt-hour', symbol: 'kWh', toBase: v => v * 3.6e6, fromBase: v => v / 3.6e6 },
      { id: 'ev', name: 'Electronvolt', symbol: 'eV', toBase: v => v * 1.602176634e-19, fromBase: v => v / 1.602176634e-19 },
      { id: 'btu', name: 'British Thermal Unit', symbol: 'BTU', toBase: v => v * 1055.06, fromBase: v => v / 1055.06 },
    ],
  },
  {
    id: 'pressure',
    name: 'Pressure',
    iconName: 'Gauge',
    units: [
      { id: 'pa', name: 'Pascal', symbol: 'Pa', toBase: v => v, fromBase: v => v },
      { id: 'kpa', name: 'Kilopascal', symbol: 'kPa', toBase: v => v * 1000, fromBase: v => v / 1000 },
      { id: 'bar', name: 'Bar', symbol: 'bar', toBase: v => v * 100000, fromBase: v => v / 100000 },
      { id: 'psi', name: 'Pound / sq inch', symbol: 'psi', toBase: v => v * 6894.757, fromBase: v => v / 6894.757 },
      { id: 'atm', name: 'Standard Atmosphere', symbol: 'atm', toBase: v => v * 101325, fromBase: v => v / 101325 },
      { id: 'torr', name: 'Torr (mmHg)', symbol: 'Torr', toBase: v => v * 133.322368, fromBase: v => v / 133.322368 },
    ],
  },
  {
    id: 'speed',
    name: 'Speed & Velocity',
    iconName: 'GaugeCircle',
    units: [
      { id: 'mps', name: 'Meter per second', symbol: 'm/s', toBase: v => v, fromBase: v => v },
      { id: 'kmh', name: 'Kilometer per hour', symbol: 'km/h', toBase: v => v / 3.6, fromBase: v => v * 3.6 },
      { id: 'mph', name: 'Mile per hour', symbol: 'mph', toBase: v => v * 0.44704, fromBase: v => v / 0.44704 },
      { id: 'knot', name: 'Knot', symbol: 'kn', toBase: v => v * 0.514444, fromBase: v => v / 0.514444 },
      { id: 'c', name: 'Speed of Light fraction', symbol: 'c', toBase: v => v * 299792458, fromBase: v => v / 299792458 },
    ],
  },
  {
    id: 'data',
    name: 'Digital Storage',
    iconName: 'HardDrive',
    units: [
      { id: 'byte', name: 'Byte', symbol: 'B', toBase: v => v, fromBase: v => v },
      { id: 'kb', name: 'Kilobyte (10³)', symbol: 'KB', toBase: v => v * 1000, fromBase: v => v / 1000 },
      { id: 'kib', name: 'Kibibyte (2¹⁰)', symbol: 'KiB', toBase: v => v * 1024, fromBase: v => v / 1024 },
      { id: 'mb', name: 'Megabyte (10⁶)', symbol: 'MB', toBase: v => v * 1e6, fromBase: v => v / 1e6 },
      { id: 'mib', name: 'Mebibyte (2²⁰)', symbol: 'MiB', toBase: v => v * 1048576, fromBase: v => v / 1048576 },
      { id: 'gb', name: 'Gigabyte (10⁹)', symbol: 'GB', toBase: v => v * 1e9, fromBase: v => v / 1e9 },
      { id: 'gib', name: 'Gibibyte (2³⁰)', symbol: 'GiB', toBase: v => v * 1073741824, fromBase: v => v / 1073741824 },
      { id: 'tb', name: 'Terabyte (10¹²)', symbol: 'TB', toBase: v => v * 1e12, fromBase: v => v / 1e12 },
    ],
  },
];
